global using System.ComponentModel.DataAnnotations;
global using System.Net;
global using Infrastructure.CommonValues;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Infrastructure.Identity;
global using Microsoft.Extensions.Options;
global using StackExchange.Redis;
global using Microsoft.OpenApi.Models;